# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 15:18


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_administrative_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_broker', to='crm.BusinessBroker', verbose_name='Business broker'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='paying_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_paying', to='crm.BusinessBroker', verbose_name='Paying authority'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_responsible', to='people.Consultant', verbose_name='Responsible'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.SalesMan', verbose_name='Salesman'),
        ),
    ]
