# Generated by Django 2.1.5 on 2019-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20181120_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='staffing',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True, 'productive': True}, to='people.Consultant'),
        ),
    ]
