# Generated by Django 4.2.19 on 2025-02-23 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_consultant_telegram_id'),
        ('crm', '0025_alter_company_businessowner'),
        ('leads', '0006_add_warmup_periodic_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_broker', to='crm.businessbroker', verbose_name='Business broker'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='paying_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_paying', to='crm.businessbroker', verbose_name='Paying authority'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_responsible', to='people.consultant', verbose_name='Responsible'),
        ),
    ]
