# Generated by Django 4.2.27 on 2026-02-26 20:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tag_tagcategory_taggeditem_tag_category'),
        ('leads', '0007_alter_lead_business_broker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
    ]
