# Generated by Django 4.2.27 on 2026-03-08 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_consultant_tags'),
        ('crm', '0025_alter_company_businessowner'),
        ('staffing', '0024_staffing_staffing_st_mission_2c479a_idx'),
        ('leads', '0009_migrate_tag_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('comment', models.TextField(blank=True)),
                ('nature', models.CharField(choices=[('PHONE_VISIO', 'Phone/Visio'), ('MEETING', 'meeting'), ('LUNCH_DINER', 'Lunch/Diner'), ('EVENT', 'Conference/Seminar')], max_length=30, verbose_name='Nature')),
                ('objective', models.CharField(choices=[('RELATIONSHIP', 'Relationship maintenance'), ('PITCH', 'Company/product pitch'), ('TARGET', 'Answer to target need')], max_length=30, verbose_name='Objective')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due')),
                ('done_date', models.DateField(blank=True, null=True, verbose_name='Done')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('state', models.CharField(choices=[('TODO_PLANNED', 'Todo/planned'), ('DONE', 'Done'), ('CANCELED', 'Annulée'), ('SLEEPING', 'En sommeil')], db_index=True, default='TODO_PLANNED', max_length=30, verbose_name='State')),
                ('business_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_broker', to='crm.businessbroker', verbose_name='Business broker')),
                ('client_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.clientorganisation', verbose_name='Client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact', verbose_name='Contact')),
                ('marketing_products', models.ManyToManyField(to='staffing.marketingproduct', verbose_name='Marketing products')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_responsible', to='people.consultant', verbose_name='Responsible')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.subsidiary', verbose_name='Subsidiary')),
            ],
        ),
    ]
