# Generated by Django 4.2.27 on 2026-03-09 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_consultant_tags'),
        ('leads', '0010_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='nature',
            field=models.CharField(choices=[('PHONE_VISIO', 'Phone/Visio'), ('MEETING', 'meeting'), ('LUNCH_DINER', 'Lunch/Diner'), ('EVENT', 'Conference/Seminar'), ('MAIL', 'Mail')], max_length=30, verbose_name='Nature'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_responsible', to='people.consultant', verbose_name='Responsible'),
        ),
    ]
