# Generated by Django 4.2.27 on 2026-03-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_activity_nature_alter_activity_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='renewal',
            field=models.BooleanField(null=True, verbose_name='Renewal'),
        ),
    ]
