# Generated by Django 4.2.27 on 2026-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_renewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='done_date',
            field=models.DateField(blank=True, null=True, verbose_name='Done date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='nature',
            field=models.CharField(choices=[('PHONE_VISIO', 'Téléphone/visio'), ('MEETING', 'rencontre'), ('LUNCH_DINER', 'Déjeuner / dîner'), ('EVENT', 'Conférence / séminaire'), ('MAIL', 'Mail')], max_length=30, verbose_name='Nature'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='objective',
            field=models.CharField(choices=[('RELATIONSHIP', 'Entretien des relations'), ('PITCH', 'Présentation société/offre'), ('TARGET', 'Réponse à une demande ciblée')], max_length=30, verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='state',
            field=models.CharField(choices=[('TODO_PLANNED', 'À faire / prévu'), ('DONE', 'Faite'), ('CANCELED', 'Annulée'), ('SLEEPING', 'En sommeil')], db_index=True, default='TODO_PLANNED', max_length=30, verbose_name='State'),
        ),
    ]
