# Generated by Django 4.2.27 on 2026-03-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_alter_company_businessowner'),
        ('leads', '0013_alter_activity_done_date_alter_activity_nature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='client_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.clientorganisation', verbose_name='Client organisation'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
    ]
