# Generated by Django 4.2.29 on 2026-03-27 17:34

from django.db import migrations, models
import django.db.models.deletion

def migrate_comment(apps, schema_editor):
    ActivityComment = apps.get_model('leads', 'ActivityComment')
    for activity in apps.get_model('leads', 'Activity').objects.exclude(comment=""):
        ActivityComment.objects.create(activity=activity, comment=activity.comment)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_activity_client_organisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.activity')),
            ],
        ),
        migrations.AlterModelOptions(
            name='activitycomment',
            options={'ordering': ['creation_date']},
        ),
        migrations.RunPython(migrate_comment),
    ]
