# Generated by Django 4.2.29 on 2026-03-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_activitycomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='comment',
        ),
    ]
