# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-03 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_clientbill_include_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierbill',
            name='state',
            field=models.CharField(choices=[('1_RECEIVED', 'Received'), ('1_VALIDATED', 'Validated'), ('2_PAID', 'Paid'), ('3_LITIGIOUS', 'Litigious'), ('4_CANCELED', 'Canceled')], default='1_RECEIVED', max_length=30, verbose_name='State'),
        ),
    ]
