# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_clientbill_client_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbill',
            name='client_deal_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Client deal id'),
        ),
    ]
