# Generated by Django 2.1.5 on 2019-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_clientbill_client_deal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbill',
            name='expenses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'chargeable': True}, to='expense.Expense'),
        ),
        migrations.AlterField(
            model_name='supplierbill',
            name='expenses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'chargeable': True}, to='expense.Expense'),
        ),
    ]
