# Generated by Django 2.2.13 on 2020-12-12 14:30

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_auto_20190819_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbill',
            name='bill_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=billing.models.BillStorage(nature='client'), upload_to=billing.models.bill_file_path, verbose_name='Bill File'),
        ),
    ]
