# Generated by Django 3.2.15 on 2022-11-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_auto_20201213_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbill',
            name='allow_duplicate_expense',
            field=models.BooleanField(default=False, verbose_name='Allow to bill twice an expense'),
        ),
    ]
