# Generated by Django 4.2.16 on 2025-03-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_expense_vat'),
        ('billing', '0025_clientbill_add_facturx_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbill',
            name='expenses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'chargeable': True}, to='expense.expense', verbose_name='expenses'),
        ),
        migrations.AlterField(
            model_name='supplierbill',
            name='expenses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'chargeable': True}, to='expense.expense', verbose_name='expenses'),
        ),
    ]
