# Generated by Django 4.2.16 on 2025-06-30 14:30

import billing.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_expense_vat'),
        ('crm', '0025_alter_company_businessowner'),
        ('billing', '0026_alter_clientbill_expenses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(default=billing.models.default_bill_id, max_length=200, unique=True, verbose_name='Bill id')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Creation date')),
                ('due_date', models.DateField(default=billing.models.default_due_date, verbose_name='Due date')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment date')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount (€ excl tax)')),
                ('amount_with_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount (€ incl tax)')),
                ('vat', models.DecimalField(decimal_places=2, default=20.0, max_digits=4, verbose_name='VAT (%)')),
                ('expenses_with_vat', models.BooleanField(default=True, verbose_name='Charge expense with VAT')),
                ('state', models.CharField(choices=[('0_DRAFT', 'Draft'), ('1_SENT', 'Sent'), ('2_PAID', 'Paid')], default='0_DRAFT', max_length=30, verbose_name='State')),
                ('bill_file', models.FileField(max_length=500, storage=billing.models.BillStorage(nature='internal'), upload_to=billing.models.bill_file_path, verbose_name='File')),
                ('add_facturx_data', models.BooleanField(default=False, verbose_name='Add Factur-X embedded information')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='crm.subsidiary', verbose_name='Buyer')),
                ('expenses', models.ManyToManyField(blank=True, limit_choices_to={'chargeable': True}, to='expense.expense', verbose_name='expenses')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='crm.subsidiary', verbose_name='Seller')),
            ],
            options={
                'ordering': ['creation_date'],
                'abstract': False,
            },
        ),
    ]
