# Generated by Django 4.2.16 on 2025-07-01 11:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0024_staffing_staffing_st_mission_2c479a_idx'),
        ('people', '0010_alter_consultant_telegram_id'),
        ('billing', '0027_internalbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalBillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(null=True)),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price (€)')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount (€ excl tax)')),
                ('amount_with_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount (€ incl tax)')),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('20.0'), max_digits=4, verbose_name='VAT (%)')),
                ('label', models.CharField(blank=True, max_length=200, null=True, verbose_name='Label')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.internalbill')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.consultant')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffing.mission')),
            ],
            options={
                'ordering': ('mission', 'month', 'consultant'),
                'abstract': False,
            },
        ),
    ]
