# Generated by Django 4.2.16 on 2025-07-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_internalbilldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalbill',
            name='lang',
            field=models.CharField(blank=True, choices=[('fr-fr', 'French'), ('en-en', 'English')], max_length=10, null=True, verbose_name='Language'),
        ),
    ]
