# Generated by Django 4.2.16 on 2025-08-26 13:55

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_internalbill_lang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalbill',
            options={'verbose_name': 'Internal Bill'},
        ),
        migrations.AlterField(
            model_name='internalbill',
            name='bill_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=billing.models.BillStorage(nature='internal'), upload_to=billing.models.bill_file_path, verbose_name='File'),
        ),
        migrations.AddIndex(
            model_name='internalbill',
            index=models.Index(fields=['state', 'creation_date'], name='billing_int_state_ee92df_idx'),
        ),
    ]
