#!/usr/bin/env python
# -*- coding: UTF-8 -*-
"""
Runs tests of all Pydici applications
@author: Aurélien Gâteau (mail@agateau.com)
@license: AGPL v3 or newer (http://www.gnu.org/licenses/agpl-3.0.html)
"""

import os
import sys

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'pydici.settings')

from django.conf import settings
from django.core.management import execute_from_command_line


def main():
    modules = [x.split('.')[-1] for x in settings.PYDICI_APPS]
    args = ['manage.py', 'test'] + modules + sys.argv[1:]
    execute_from_command_line(args)


if __name__ == '__main__':
    main()
