#!/usr/bin/env python
"""
Runs tests of all Pydici applications
"""

import os
import sys

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'pydici.settings')

from django.conf import settings
from django.core.management import execute_from_command_line


def main():
    modules = [x.split('.')[-1] for x in settings.PYDICI_APPS]
    args = ['manage.py', 'test'] + modules + sys.argv[1:]
    execute_from_command_line(args)


if __name__ == '__main__':
    main()
