# Generated by Django 4.2.27 on 2026-02-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_groupfeature_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'ordering': ['name'], 'verbose_name': 'Tag Category', 'verbose_name_plural': 'Tag Categories'},
        ),
    ]
