# Generated by Django 4.2.27 on 2026-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_tagcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeditem',
            name='level',
            field=models.CharField(blank=True, choices=[('1_BEGINNER', 'Beginner'), ('2_INTERMEDIATE', 'Intermediate'), ('3_ADVANCED', 'Avancé')], max_length=30, null=True, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='nature',
            field=models.CharField(blank=True, choices=[('1_KNOWLEDGE', 'Knowledge'), ('1_WISH', 'Wish')], max_length=30, null=True, verbose_name='Nature'),
        ),
    ]
