# Generated by Django 4.2.30 on 2026-04-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_taggeditem_level_taggeditem_nature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
