# Generated by Django 3.2.16 on 2022-12-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='trigger_down',
            field=models.CharField(blank=True, choices=[('ARCHIVED_MISSION', 'Quand une mission est archivée'), ('RATES_DEFINED', 'When rates are defined'), ('FORECASTING_ALMOST_DONE', 'When forecasting it mostly done'), ('FIRST_BILL_REQUESTED', 'When the first bill has been requested'), ('DELIVERY_DOC_STORED', 'When at least one delivery document is stored')], max_length=50, null=True, verbose_name='Trigger down'),
        ),
    ]
