# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 17:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20181120_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='state',
            field=models.CharField(choices=[('REQUESTED', 'requested'), ('VALIDATED', 'validated'), ('REJECTED', 'rejected'), ('NEEDS_INFORMATION', 'needs information'), ('CONTROLLED', 'controlled'), ('PAID', 'paid')], default='REQUESTED', max_length=20, verbose_name='state'),
        ),
    ]
