# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20181120_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='state',
            field=models.CharField(choices=[(b'REQUESTED', 'requested'), (b'VALIDATED', 'validated'), (b'REJECTED', 'rejected'), (b'NEEDS_INFORMATION', 'needs information'), (b'CONTROLLED', 'controlled'), (b'PAID', 'paid')], default=b'REQUESTED', max_length=20, verbose_name='state'),
        ),
    ]
