# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-13 22:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='state',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('NEEDS_INFORMATION', 'Needs information'), ('CONTROLLED', 'Controlled'), ('PAID', 'Paid')], default='REQUESTED', max_length=20, verbose_name='state'),
        ),
    ]
