# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-13 22:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_auto_20190113_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
