# Generated by Django 2.2.5 on 2019-09-23 21:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_auto_20190113_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='VAT (€)'),
        ),
    ]
