# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20181120_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbroker',
            name='billing_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name used for billing'),
        ),
    ]
