# Generated by Django 2.2.10 on 2020-03-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_businessbroker_billing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='expectations',
            field=models.CharField(choices=[('1_NONE', 'Aucune'), ('2_DECREASING', 'Décroissance'), ('3_FLAT', 'Inchangée'), ('4_INCREASING', 'Croissance')], default='3_FLAT', max_length=30, verbose_name='Expectations'),
        ),
    ]
