# Generated by Django 2.2.13 on 2020-12-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20200331_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vat_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='VAT id'),
        ),
        migrations.AddField(
            model_name='company',
            name='vat_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='VAT id'),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='vat_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='VAT id'),
        ),
    ]
