# Generated by Django 3.2.16 on 2022-12-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20201213_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorganisation',
            name='legal_description',
            field=models.TextField(blank=True, null=True, verbose_name='Legal description'),
        ),
        migrations.AddField(
            model_name='clientorganisation',
            name='legal_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='VAT id'),
        ),
        migrations.AddField(
            model_name='clientorganisation',
            name='vat_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='VAT id'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='VAT id'),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='legal_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='VAT id'),
        ),
    ]
