# Generated by Django 3.2.16 on 2022-12-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20221210_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorganisation',
            name='legal_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Legal id'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Legal id'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='legal_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Legal id'),
        ),
    ]
