# Generated by Django 3.2.16 on 2022-12-10 17:30

from django.db import migrations

def forwards(apps, schema_editor):
    Client = apps.get_model("crm", "Client")
    for client in Client.objects.exclude(vat_id__isnull=True):
        client.organisation.vat_id = client.vat_id
        client.organisation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20221210_1725'),
    ]

    operations = [
        migrations.RunPython(forwards),
        migrations.RemoveField(
            model_name='client',
            name='vat_id',
        ),
    ]
