# Generated by Django 3.2.16 on 2022-12-11 17:10

from django.db import migrations

def forwards(apps, schema_editor):
    Client = apps.get_model("crm", "Client")
    for client in Client.objects.all():
        client.organisation.billing_city = client.billing_city
        client.organisation.billing_country = client.billing_country
        client.organisation.billing_street = client.billing_street
        client.organisation.billing_zipcode = client.billing_zipcode
        client.organisation.city = client.city
        client.organisation.country = client.country
        client.organisation.street = client.street
        client.organisation.zipcode = client.zipcode
        client.organisation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20221210_1800'),
    ]

    operations = [
        migrations.RunPython(forwards),
        migrations.RemoveField(
            model_name='client',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='billing_street',
        ),
        migrations.RemoveField(
            model_name='client',
            name='billing_zipcode',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='street',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zipcode',
        ),
    ]
