# Generated by Django 3.2.16 on 2022-12-11 21:56

from django.db import migrations
import django_countries.fields
from django.db.models import CharField
from django.db.models.functions import Length

def forwards(apps, schema_editor):
    ClientOrganisation = apps.get_model("crm", "ClientOrganisation")
    Company = apps.get_model("crm", "Company")
    Subsidiary = apps.get_model("crm", "Subsidiary")
    for model in (ClientOrganisation, Company, Subsidiary):
        # Fix some common used countries in known deployements
        for country, country_code in (("France", "FR"), ("Paris", "FR"), ("USA", "US"),
                                      ("Suisse", "CH"), ("Switzerland", "CH"),
                                      ("Hong-Kong SAR (China)", "HK"), ("Maroc", "MA"),
                                      ("Singapore", "SG"),
                                      ("Iceland", "IS"), ("Germany", "DE"), ("Italie", "IT")):
            model.objects.filter(country=country).update(country=country_code)
            model.objects.filter(billing_country=country).update(billing_country=country_code)
        # truncate to 2 first letters for others
        CharField.register_lookup(Length, 'length')
        for i in model.objects.filter(country__length__gt=2):
            i.country = i.country[:2]
            i.save()
        for i in model.objects.filter(billing_country__length__gt=2):
            i.billing_country = i.billing_country[:2]
            i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20221211_1710'),
    ]

    operations = [
        migrations.RunPython(forwards),
        migrations.AlterField(
            model_name='clientorganisation',
            name='billing_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='clientorganisation',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='billing_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='billing_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
    ]
