# Generated by Django 3.2.18 on 2023-03-26 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20221211_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='clientorganisation',
            name='business_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.businesssector', verbose_name='Business sector'),
        ),
        migrations.AddField(
            model_name='company',
            name='business_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.businesssector', verbose_name='Business sector'),
        ),
    ]
