# Generated by Django 3.2.19 on 2023-06-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20230326_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssector',
            options={'verbose_name': 'Business sector', 'verbose_name_plural': 'Business sectors'},
        ),
    ]
