# Generated by Django 4.2.19 on 2025-02-23 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_consultant_telegram_id'),
        ('crm', '0024_alter_businesssector_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='businessOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_business_owner', to='people.consultant', verbose_name='Business owner'),
        ),
    ]
