# Generated by Django 4.2.27 on 2026-03-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_alter_company_businessowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativecontact',
            name='default_fax',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='fax',
        ),
    ]
