# Generated by Django 5.2.17 on 2026-10-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_remove_administrativecontact_default_fax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
    ]
