# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20170817_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_as_manager', to='people.Consultant'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='staffing_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_as_staffing_manager', to='people.Consultant'),
        ),
    ]
