# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-10 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20181120_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='subcontractor_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Supplier'),
        ),
    ]
