# Generated by Django 3.2.18 on 2023-03-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_compute_consultants_tasks_periodic_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='telegram_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
