# Generated by Django 4.2.27 on 2026-02-26 21:57

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tag_tagcategory_taggeditem_tag_category'),
        ('people', '0010_alter_consultant_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
    ]
