# Generated by Django 4.2.27 on 2026-09-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_consultant_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Consultant location',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='consultant',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.consultantlocation', verbose_name='Location'),
        ),
    ]