# Generated by Django 5.2.17 on 2026-09-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_consultantlocation_consultant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantlocation',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='consultantlocation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
