BEGIN;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE `auth_user`;
TRUNCATE `auth_group`;
TRUNCATE `people_consultantprofile`;
TRUNCATE `staffing_timesheet`;
TRUNCATE `billing_clientbill`;
TRUNCATE `crm_supplier`;
TRUNCATE `staffing_financialcondition`;
TRUNCATE `staffing_mission`;
TRUNCATE `auth_group_permissions`;
TRUNCATE `crm_missioncontact`;
TRUNCATE `billing_supplierbill`;
TRUNCATE `expense_expensecategory`;
TRUNCATE `core_parameter`;
TRUNCATE `leads_lead_staffing`;
TRUNCATE `crm_businesssector`;
TRUNCATE `billing_supplierbill_expenses`;
TRUNCATE `crm_clientorganisation`;
TRUNCATE `staffing_holiday`;
TRUNCATE `auth_user_groups`;
TRUNCATE `people_salesman`;
TRUNCATE `staffing_staffing`;
TRUNCATE `crm_administrativecontact`;
TRUNCATE `django_session`;
TRUNCATE `staffing_analyticcode`;
TRUNCATE `people_rateobjective`;
TRUNCATE `billing_clientbill_expenses`;
TRUNCATE `expense_expensepayment`;
TRUNCATE `django_celery_beat_periodictasks`;
TRUNCATE `crm_company`;
TRUNCATE `core_groupfeature`;
TRUNCATE `billing_billexpense`;
TRUNCATE `crm_contact_contact_points`;
TRUNCATE `staffing_mission_contacts`;
TRUNCATE `leads_lead`;
TRUNCATE `crm_subsidiary`;
TRUNCATE `crm_businessbroker`;
TRUNCATE `billing_billdetail`;
TRUNCATE `crm_contact`;
TRUNCATE `staffing_lunchticket`;
TRUNCATE `crm_administrativefunction`;
TRUNCATE `people_consultant`;
TRUNCATE `crm_client`;
TRUNCATE `expense_expense`;
TRUNCATE `taggit_taggeditem`;
TRUNCATE `leads_stateproba`;
TRUNCATE `staffing_marketingproduct`;
SET FOREIGN_KEY_CHECKS = 1;
COMMIT;

