# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0003_auto_20160228_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_responsible', to='people.Consultant', verbose_name='Responsible'),
        ),
    ]
