# Generated by Django 2.1.5 on 2019-08-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0004_auto_20181120_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcondition',
            name='mission',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='staffing.Mission'),
        ),
        migrations.AlterField(
            model_name='staffing',
            name='mission',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='staffing.Mission'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='mission',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='staffing.Mission'),
        ),
    ]
