# Generated by Django 2.2.5 on 2019-12-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0005_auto_20190819_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='analytic_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffing.AnalyticCode'),
        ),
    ]
