# Generated by Django 2.2.5 on 2019-12-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0007_auto_20191206_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticcode',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
