# Generated by Django 2.2.10 on 2020-02-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0008_auto_20191206_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='mission',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
