# Generated by Django 2.2.10 on 2020-03-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0009_auto_20200227_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='management_mode',
            field=models.CharField(blank=True, choices=[('LIMITED', 'Limited'), ('ELASTIC', 'Elastic')], max_length=30, null=True, verbose_name='Management mode'),
        ),
    ]
