# Generated by Django 2.2.10 on 2020-03-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0010_mission_management_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='management_mode',
            field=models.CharField(choices=[('LIMITED', 'Limité'), ('ELASTIC', 'Élastique'), ('NONE', 'None')], default='NONE', max_length=30, verbose_name='Management mode'),
        ),
    ]
