# Generated by Django 3.2.15 on 2022-08-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20201213_1508'),
        ('staffing', '0012_auto_20210116_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.subsidiary', verbose_name='Subsidiary')),
            ],
            options={
                'unique_together': {('code', 'subsidiary')},
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='marketing_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffing.marketingproduct', verbose_name='marketing product'),
        ),
    ]
