# Generated by Django 3.2.15 on 2022-09-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0013_auto_20220826_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='min_charge_per_day',
            field=models.FloatField(default=0, verbose_name='Min charge per day'),
        ),
    ]
