# Generated by Django 3.2.18 on 2023-03-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0015_alter_mission_management_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='management_mode',
            field=models.CharField(choices=[('LIMITED', 'Limité'), ('LIMITED_INDIVIDUAL', 'Limité individuel'), ('ELASTIC', 'Élastique'), ('NONE', 'Aucun')], default='NONE', max_length=30, verbose_name='Management mode'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='working_date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
    ]
