# Generated by Django 3.2.18 on 2023-03-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0017_alter_staffing_options'),
        ('staffing', '0017_auto_20230307_0000'),
    ]

    operations = [
    ]
