# Generated by Django 3.2.19 on 2023-06-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0018_merge_20230310_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='min_charge_per_day',
            new_name='min_charge_multiple_per_day',
        ),
    ]
