# Generated by Django 4.2.19 on 2025-02-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_consultant_telegram_id'),
        ('staffing', '0021_mission_client_deal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_responsible', to='people.consultant', verbose_name='Responsible'),
        ),
    ]
