# Generated by Django 4.2.19 on 2025-03-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0022_alter_mission_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='always_displayed',
            field=models.BooleanField(default=False, verbose_name='Always displayed'),
        ),
    ]
