# Generated by Django 4.2.16 on 2025-04-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0023_mission_always_displayed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staffing',
            index=models.Index(fields=['mission', 'consultant'], name='staffing_st_mission_2c479a_idx'),
        ),
    ]
