# Generated by Django 4.2.30 on 2026-06-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0024_staffing_staffing_st_mission_2c479a_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holiday',
            new_name='PublicHoliday',
        ),
        migrations.AlterModelOptions(
            name='publicholiday',
            options={'verbose_name': 'Public Holiday'},
        ),
    ]
