# Generated by Django 4.2.30 on 2026-06-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_consultant_tags'),
        ('staffing', '0025_rename_holiday_publicholiday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayBalanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('monthly_increment', models.FloatField(default=0, verbose_name='Monthly Increment')),
                ('missions', models.ManyToManyField(blank=True, to='staffing.mission')),
            ],
            options={
                'verbose_name': 'Holiday Balance Type',
                'verbose_name_plural': 'Holiday Balance Types',
            },
        ),
        migrations.CreateModel(
            name='HolidayBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, verbose_name='Balance')),
                ('balance_date', models.DateField(verbose_name='Balance Date')),
                ('balance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffing.holidaybalancetype')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.consultant')),
            ],
            options={
                'unique_together': {('consultant', 'balance_type')},
            },
        ),
    ]
