# Generated by Django 4.2.30 on 2026-06-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0026_holidaybalancetype_holidaybalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaybalancetype',
            name='excluded_missions',
            field=models.ManyToManyField(blank=True, related_name='excluded_missions', to='staffing.mission'),
        ),
    ]
