# Generated by Django 4.2.30 on 2026-06-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0027_holidaybalancetype_excluded_missions'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaybalancetype',
            name='upstream_balance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downstream_balance_type', to='staffing.holidaybalancetype'),
        ),
    ]
