# Generated by Django 4.2.30 on 2026-06-25 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0028_holidaybalancetype_upstream_balance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaybalancetype',
            name='upstream_balance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downstream_balance_type', to='staffing.holidaybalancetype'),
        ),
    ]
